### ISSUE TITLE
「友だちリストに友だちになったばかりのユーザが表示されていません」と出てしまう

### ISSUE THREAD

**Issue by yuki2006** [isucon/isucon5-qualify#6]
昨年のisuconの復習として活用させていただいております。

>   "violations" : [ {
>     "type" : "CHECK LEFT FOOTPRINTS OF OTHERS",
>     "description" : "友だちリストに友だちになったばかりのユーザが表示されていません",
>     "number" : 1
>   }

と出るようになりました。

質問なのですが、
https://github.com/isucon/isucon5-qualify/blob/a8716af085305a7cd4897c86b293f412e46124ce/bench/src/main/java/net/isucon/isucon5q/bench/scenario/BootstrapChecker.java#L298

BootstrapChecker.javaの298行目ですが、

footprintDateは、286行目のタイミング時の時間かと思いますが、
まずfilterでfootprintDateと同じものだけ残って
user2Pathとuser3Pathだけ残して2件じゃなければエラーというものだと読みました。

この時、profileページを見ているので足跡が残りますが、user1から見るとuser2とuser3だと処理のタイミング的に1秒ずれてしまう可能性があり、それでテストが通らないのではないと思いましたが、いかがでしょうか。
（処理が高速化されていれば、確率は低くなるのだと思いますが）

また304行目のエラーメッセージも足あとに関するエラーメッセージにしたほうが良いではないかと思いますが、いかがでしょうか。

見当違いでしたら、申し訳ありません。

**Comment by tagomoris** [comment]
304行目のエラーメッセージが間違っているのはそのとおりです。(pull-requestをお待ちしています)

足跡について「処理のタイミング的に1秒ずれてしまう可能性があり」というのは質問の意味がわかりません。user2/user3がuser1のプロフィールを表示しているのは(ベンチマークツール側から見て)user1のプロフィール更新よりも前の話であり、であれば「1秒後までにGETの結果に反映されていること」というレギュレーションを満たすためには、ここで2件の足跡が残っている(表示されている)必要があります。
「処理のタイミング的に1秒ずれて」しまうのであれば、それはアプリケーションの問題としてfailになるべきもののように思えます。

**Comment by yuki2006** [comment]
お返事ありがとうございます。

例えばですが、user2 が 12:00:00.90  に足跡を残し、user3が12:00:01.10に足跡が残った場合
（これはアクセス時間というより、内部実装的にデータベースに足跡が残った時間ということになりますが）

それぞれ時間的に12:00:00 , 12:00:01となりfootprintDateでfilterするとどちらかしか残らないように思いました。

見当違いでしたら申し訳ないですが。

**Comment by tagomoris** [comment]
`footprintDate` は date であって time を含まない(see DateTimeFormatter.ISO_LOCAL_DATE)ので、user2とuser3が偶然日をまたがない限りは大丈夫です。つまり例として 23:59:59.999 と 00:00:00.001 になったら問題が起きますね。
が、予選は日中に開催されることもあるので現実的には問題にならないだろうとして除外しています。簡単に対応できる方法があるならmergeすることはやぶさかではありませんが。

**Comment by yuki2006** [comment]
申し訳ないです。
`DateTimeFormatter .ISO_LOCAL_DATE); // yyyy-MM-dd`
を見落としておりました。
コメントも書かれていたのに頭に入ってなかったです。。
申し訳ないです。

（きちんと調べきれてないですが、単純にこちらのアプリケーションの処理時間がかかりすぎてただけだったのかもしれません。）
